apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratel
spec:
  template:
    spec:
      containers:
      - name: ratel
        resources:
          limits:
            cpu: 1200m
            memory: 1024Mi
          requests:
            cpu: 1000m
            memory: 512Mi
