apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

patchesStrategicMerge:
- deployment.yaml
- autoscalar.yaml

resources:
- ../base

commonLabels:
  app: ratel

images:
- name: /
  newTag: dev-2021-12-08T15-39
- name: 885406856042.dkr.ecr.us-east-1.amazonaws.com/cf-ecr-dev
  newTag: v1.1502431146
