apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- autoscalar.yaml
- service.yaml

# configMapGenerator:
# - name: ratel
# - name: ratel-gcp

commonLabels:
  app: ratel
