kind: Service
apiVersion: v1
metadata:
  labels:
    app: ratel
  name: ratel-svc
spec:
  selector:
    app: ratel
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080